---
title: "Ammonia Volatilization Emission Factor"
author: "Chih-Yu Hung"
date: "2024-02-27, Revised in May"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
load("../Input/Crop type and real fertilizer_2016-2022.RData")
```

## Objectives
Estimate indirect N2O emissions from volatilization.
Input data:
Real fertilizer usage: Input/Crop type and real Fertilizer_2016-2022.RData
Function:
Function for Indirect N2O EF_volatilization


```{r EF table}
#Merge data for fertilizers 
App_Fert <- App %>%
  inner_join(Fert, by = c("Year" = "Inv_Year", "Province_Sale_ID" = "Province_Sale_ID", "Fert_ID" = "Fert_ID")) 

#Merge data for soil conditions
App_Fert_Soil <- App_Fert %>%
  inner_join(Soil, by = c("Province_ID" = "Province", "EcoDistrict" = "EcoDistrict")) 


# Add application method proportion
West <- c("BC", "AB","SK","MB")

App_Fert_Soil <- App_Fert_Soil %>%
  mutate(Coast = case_when(
    Province_ID %in% West ~ "West",
    !(Province_ID %in% West) ~ "East"
  )
  )

App_Fert_Soil <- App_Fert_Soil %>%
  inner_join(App.prop, by = c("Coast" = "Coast", "Fert_ID" = "Fertilizer_ID", "Method_ID" = "Method_ID"))

#get rid of columns I don't need
App_Fert_Soil <- App_Fert_Soil %>%
  select(-Province_Sale_ID,-Fert_ID,-Crop_Type,-Emissions,-Coast,-ID)


#Add corrected applied fertilizer amount in the specific year and ecodistrict
App_Fert_Soil <- App_Fert_Soil %>%
  inner_join(Fert.amount, by = c("Year" = "Inv_Year_ID", "Province_ID" = "Province_ID", "EcoDistrict" = "Ecodistrict_ID")) %>%
  select(-Fertilizer_Applied, Fertilizer_Applied = N_Applied_kg)


```

##Prepare Ecodistrict and Ecozone data
``` {r Ecozone}
#Merge data for soil conditions
Coef_vola <- Coef_vola %>%
  inner_join(EF4, by = c("Province_ID" = "Province_ID", "EcoDistrict" = "ECODISTRIC")) 



#drop unwanted columns
Coef_vola <- Coef_vola %>%
  select(-ECOZONE,-ZONE_NAME)

```



