---
title: "Prepare Data for volatilization function_US"
author: "Chih-Yu Hung"
date: "2025-05-26"
output: html_document
---

```{r setup, include=FALSE}
source("../setup.R")
us_outputs <- function(...) {
  here("..", "..", "US data", "Outputs", ...)   # climb up twice, then across
}
```

## Objectives
This file prepare the data to be "SiteData" and will calculate the volatilization and the EF with `Function for Indirect N2O EF_volatilization` 

```{r Read data and explanation}
#Example for SiteData
#   RegionID:        suggest using HUP
#   ProvinceID:      Province or State ID
#   Year:            
#   CropID:          Name of crop
#   Crop_coef:       characteristic, Annual or Perennial
#   Fert_coef:       characteristic, Urea, Urea ammonia, Anhydrous ammonia, and Other
#   Method_ID_coef:  numeric, Broadcast (1) and Incorporated (2 or 3)
#   SoilpH:          numeric, -1 (<7.25) and 0 (>7.25)
#   SoilCEC:         numeric, or -1 (<250) and 0 (>250)
#   Climate          Temperate or Tropical
#   Percentage:      Percentage of soil condition (the combination of pH and CEC, sum of them must be 1)
#   Fraction:        Fraction of fertilizer
#   Proportion:      Proportion of application method
#   Fertilizer_Applied: The amount of applied fertilizer (kg)
#   Ecozone:         Ecozone for the Region

load(us_outputs("0.2_US_volatilization_GrainAgg.RData"))
load(us_outputs("0.2_US_volatilization_GrainSplit.RData"))

```

## Prepare data to be SiteData

```{r Grain Agg}

#Determine ecozone (wet vs dry based on PRE and PET)
US_vola_GrainAgg <- US_vola_GrainAgg %>%
           mutate(Ecozone = case_when(
             PRE_Y >= PET_Y ~ "Wet zone",
             PRE_Y < PET_Y ~ "Dry zone"),
             Climate = "Temperate",
             Crop_coef = "Annual"
             )


#Rename the SiteData to fit the function
SiteData <- US_vola_GrainAgg %>%
  rename(Method_ID_coef= Method_ID,
         Fertilizer_Applied = Fert_LCA_kg,
         ) %>%
  mutate(CropID = crop_mapping(CROP, CLASS)) %>%
  filter(!is.na(CropID))%>%  # Remove unwanted crops
  mutate(RegionID = str_c(CropID, STATE, COUNTY, YEAR, sep = "_"))%>% #add RegionID
  select(-CROP, -CLASS, -PRE_Y, -PET_Y, -COUNTY) %>%
  rename(ProvinceID = STATE, Year = YEAR) #easy to work with Canada's data

#Reorder the columns
SiteData <- SiteData %>%
  select(RegionID, ProvinceID, Year, CropID, Crop_coef, Fert_coef, Method_ID_coef, SoilpH, SoilCEC, Climate, Percentage, Fraction, Proportion, Fertilizer_Applied, Ecozone)

#save(SiteData, file = "../Input/US_volatilization_2018-2022_GrainAgg.RData") #Faster as the file is large,9424000 obs x 15 variables

```


## Prepare data to be SiteData

```{r Grain Split}

#Determine ecozone (wet vs dry based on PRE and PET)
US_vola_GrainSplit <- US_vola_GrainSplit %>%
           mutate(Ecozone = case_when(
             PRE_Y >= PET_Y ~ "Wet zone",
             PRE_Y < PET_Y ~ "Dry zone"),
             Climate = "Temperate",
             Crop_coef = "Annual"
             )


#Rename the SiteData to fit the function
SiteData <- US_vola_GrainSplit %>%
  rename(Method_ID_coef= Method_ID,
         Fertilizer_Applied = Fert_LCA_kg,
         ) %>%
  mutate(CropID = crop_mapping(CROP, CLASS, UTIL_PRACTICE_DESC)) %>%
  filter(!is.na(CropID) & !is.na(Fertilizer_Applied))%>%  # Remove unwanted crops, sorghum silage has NA
  mutate(RegionID = str_c(CropID, STATE, COUNTY, YEAR, sep = "_"))%>% #add RegionID
  select(-CROP, -CLASS, -PRE_Y, -PET_Y, -COUNTY) %>%
  rename(ProvinceID = STATE, Year = YEAR) #easy to work with Canada's data

#Reorder the columns
SiteData <- SiteData %>%
  select(RegionID, ProvinceID, Year, CropID, Crop_coef, Fert_coef, Method_ID_coef, SoilpH, SoilCEC, Climate, Percentage, Fraction, Proportion, Fertilizer_Applied, Ecozone)

save(SiteData, file = "../Input/US_volatilization_2018-2022_GrainSplit.RData") #Faster as the file is large,11388096 obs x 15 variables

```

