---
title: "Prepare Data for volatilization function_US"
author: "Chih-Yu Hung"
date: "2024-02-27"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

## Objectives
This file prepare the data to be "SiteData" and will calculate the volatilization and the EF with `Function for Indirect N2O EF_volatilization` 

```{r Read data and explanation}
#Example for SiteData
#   RegionID:        suggest using HUP
#   ProvinceID:      Province or State ID
#   Year:            
#   CropID:          Name of crop
#   Crop_coef:       characteristic, Annual or Perennial
#   Fert_coef:       characteristic, Urea, Urea ammonia, Anhydrous ammonia, and Other
#   Method_ID_coef:  numeric, Broadcast (1) and Incorporated (2 or 3)
#   SoilpH:          numeric, -1 (<7.25) and 0 (>7.25)
#   SoilCEC:         numeric, or -1 (<250) and 0 (>250)
#   Climate          Temperate or Tropical
#   Percentage:      Percentage of soil condition (the combination of pH and CEC, sum of them must be 1)
#   Fraction:        Fraction of fertilizer
#   Proportion:      Proportion of application method
#   Fertilizer_Applied: The amount of applied fertilizer (kg)
#   Ecozone:         Ecozone for the Region

Soil <- read.csv("../Input/ACTIVITYDATA-EcoDistrict_Soils.csv") #Ecod,pH,CEC,proportion
Fert <- read.csv("../Input/ACTIVITYDATA-Fertilzer_Proportion.csv") #Year, Prov, Fert type, proportion
EF4 <- read.csv("../Input/EF4.csv") #Ecod, Ecozone, Prov
App <- read.csv("../Input/Application method.csv") #Year, Prov, Ecod, application, App amount
App.prop <- read.csv("../Input/Fertilizer_Propor_Methods.csv") #Fertilzer type, application type, coast and proportion

#Fertilization (kg) for specific crop in specific year
Fert_crop_GrainSplit <- read_rds("../Input/CA_Direct_2016-2022_GrainSplit.rds") 
Fert_crop_GrainAgg <- read_rds("../Input/CA_Direct_2016-2022_GrainAgg.rds") 
#Sam data but Without Silage corn
#Fert_crop <- read_rds("../Input/CA_Direct_2016-2022_WO_Silage.rds") 



#Abandoned since it has annual crop only while we want specific crops. 
#Fert.amount <- read.csv("Input/N2OCOMP_Indirect_Emissions_ED_with_Descr.csv")
#Downsize the Fert.amount, We need FSN only.
#Fert.amount <- Fert.amount[Fert.amount$N_SOURCE == "FSN" & Fert.amount$Crop_System == "Annual",]
#Fert.amount <- Fert.amount %>%
#  select(Inv_Year_ID,Province_ID,Ecodistrict_ID,Crop_System,N_Applied_kg)
```


## Prepare data to be SiteData

```{r EF table}

#Merge data for fertilizers to know fraction of fertilizer
App_Fert <- App %>%
  inner_join(Fert, by = c("Year" = "Inv_Year", "Province_Sale_ID" = "Province_Sale_ID", "Fert_ID" = "Fert_ID")) 

#Merge data for soil conditions
App_Fert_Soil <- App_Fert %>%
  inner_join(Soil, by = c("Province_ID" = "Province", "EcoDistrict" = "EcoDistrict")) 


# Add application method proportion
West <- c("BC", "AB","SK","MB")

App_Fert_Soil <- App_Fert_Soil %>%
  mutate(Coast = case_when(
    Province_ID %in% West ~ "West",
    !(Province_ID %in% West) ~ "East"
  )
  )

App_Fert_Soil <- App_Fert_Soil %>%
  inner_join(App.prop, by = c("Coast" = "Coast", "Fert_ID" = "Fertilizer_ID", "Method_ID" = "Method_ID"))

#get rid of columns I don't need
App_Fert_Soil <- App_Fert_Soil %>%
  select(-Province_Sale_ID,-Fert_ID,-Crop_Type,-Emissions,-Coast,-ID) %>%
  filter(Year >= 2016)

#Add Ecozone for EF4
App_Fert_Soil <- App_Fert_Soil %>%
  inner_join(EF4, by = c("Province_ID" = "Province_ID", "EcoDistrict" = "ECODISTRIC")) 

#Add corrected applied fertilizer amount in the specific year and ecodistrict and crop
#Grain Split
SiteData_GrainSplit <- App_Fert_Soil %>%
  inner_join(Fert_crop_GrainSplit, by = c("Year", "Province_ID" , "EcoDistrict" = "Ecodistrict")) %>%
  select(-Fertilizer_Applied.x, -Crop_f:-NSource) %>%
  rename(ProvinceID = Province_ID,
         Fert_coef = Fert_Name,
         Method_ID_coef= Method_ID,
         SoilpH = Acid_Soil,
         SoilCEC = Poor_Soil,
         Fertilizer_Applied = Fertilizer_Applied.y,
         Ecozone = ZONE_NAME
         ) %>%
  mutate(Crop_coef = "Annual",
         Climate = "Temperate")%>%
  select(RegionID, ProvinceID, EcoDistrict ,Year, CropID, Crop_coef, Fert_coef, Method_ID_coef, SoilpH, SoilCEC, Climate, Percentage, Fraction, Proportion, Fertilizer_Applied, Ecozone)


#GrainAgg
SiteData_GrainAgg <- App_Fert_Soil %>%
  inner_join(Fert_crop_GrainAgg, by = c("Year", "Province_ID" , "EcoDistrict" = "Ecodistrict")) %>%
  select(-Fertilizer_Applied.x, -Crop_f:-NSource) %>%
  rename(ProvinceID = Province_ID,
         Fert_coef = Fert_Name,
         Method_ID_coef= Method_ID,
         SoilpH = Acid_Soil,
         SoilCEC = Poor_Soil,
         Fertilizer_Applied = Fertilizer_Applied.y,
         Ecozone = ZONE_NAME
         ) %>%
  mutate(Crop_coef = "Annual",
         Climate = "Temperate") %>%
  select(RegionID, ProvinceID, EcoDistrict ,Year, CropID, Crop_coef, Fert_coef, Method_ID_coef, SoilpH, SoilCEC, Climate, Percentage, Fraction, Proportion, Fertilizer_Applied, Ecozone)

```


### Output the SiteData
Show head to data to see the data structure 

```{r Output data}
#write.csv(SiteData, "../Input/CA_volatilization_2016-2022.csv")
#save(SiteData,   file = "../Input/CA_volatilization_2016-2022.RData") #Faster as the file is large, 1330992 obs x 16 variables
#save(SiteData,   file = "../Input/CA_volatilization_2016-2022_WO_Silage.RData") #Faster as the file is large, 1330992 obs x 16 variables

save(SiteData_GrainAgg,   file = "../Input/CA_volatilization_2016-2022_GrainAgg.RData") #Faster as the file is large, 1330992 obs x 16 variables
save(SiteData_GrainSplit,   file = "../Input/CA_volatilization_2016-2022_GrainSplit.RData") #Faster as the file is large, 1478880 obs x 16 variables

head(SiteData)


```


